---
# Source: grafana/templates/clusterrole.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: grafana
    chart: grafana-4.0.4
    release: grafana
    heritage: Tiller
  name: grafana-clusterrole
rules: []
