---
# Source: grafana/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: grafana-kustomize
  labels:
    app: grafana
    chart: grafana-4.0.4
    release: grafana
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "OFR2Um5JUzV0SEx2M2hvazh6Z2tjSlRmMlkxckNRa2lDM3hxc1BJeg=="
  ldap-toml: ""
